version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    volumes:
      - ./docs:/app/docs
      - ./models_cache:/app/models_cache
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=mistral
      - JWT_SECRET=${JWT_SECRET:-supersecretkey123456789supersecretkey123} # Default value as fallback
    depends_on:
      - ollama
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001
      - NEXT_PUBLIC_OLLAMA_URL=http://localhost:11434
      - JWT_SECRET=${JWT_SECRET:-supersecretkey123456789supersecretkey123} # Same secret as backend
    depends_on:
      - backend
  
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: 